/* ===========================
   Core Data Types
   =========================== */

export interface DocumentImage {
  id: string;
  dataUrl: string;
  alt?: string;
}

export interface ModuleData {
  id: string;
  title: string;
  notes: string;
  images: DocumentImage[];
  dashboard: DashboardData | null;
  createdAt: number;
  updatedAt: number;
  xp: number;
}

/* ===========================
   Dashboard — generated by a single LLM call
   =========================== */

export interface DashboardData {
  moduleTitle: string;
  moduleSynthesis: ModuleSynthesis;
  coreConcepts: CoreConcept[];
  contextMap: ContextMap;
  scenario: Scenario;
  diagnosticQuestions: DiagnosticQuestion[];
  masteryProgress: MasteryProgress;
}

export interface ModuleSynthesis {
  summary: string;
  keyTakeaways: string[];
}

export interface CoreConcept {
  id: string;
  term: string;
  definition: string;
  analogy: string;
  xp: number;
}

export interface ContextMap {
  topic: string;
  nodes: ContextMapNode[];
  edges: ContextMapEdge[];
}

export interface ContextMapNode {
  id: string;
  label: string;
  description: string;
  category: 'root' | 'concept' | 'subtopic' | 'example' | 'related';
  importance: number; // 1-5
}

export interface ContextMapEdge {
  source: string;
  target: string;
  label: string;
}

export interface Scenario {
  title: string;
  context: string;
  options: ScenarioOption[];
}

export interface ScenarioOption {
  id: string;
  text: string;
  isCorrect: boolean;
  explanation: string;
}

export interface DiagnosticQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  distractorsExplanation?: string;
  topic?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export interface MasteryProgress {
  totalXp: number;
  level: number;
  streak: number;
  conceptsMastered: number;
  quizzesPassed: number;
}

/* ===========================
   Practice Duel Types
   =========================== */

export type DuelPhase = 'idle' | 'preparing' | 'playing' | 'done';

export interface DuelQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  distractorsExplanation?: string;
}

export interface DuelState {
  phase: DuelPhase;
  questions: DuelQuestion[];
  currentIndex: number;
  playerScore: number;
  rivalScore: number;
  playerLives: number;
  combo: number;
  comboLevel: number;
  timeLeft: number;
  hasShield: boolean;
  isAnswered: boolean;
  selectedAnswer: number | null;
  highScore: number;
  hintOpen: boolean;
}

/* ===========================
   Combo System
   =========================== */

export type ComboLevel = 'none' | 'bronze' | 'silver' | 'gold' | 'platinum';

export const COMBO_THRESHOLDS = [0, 3, 5, 10, 20] as const;
export const COMBO_MULTIPLIERS = [1, 3, 5, 10, 20] as const;
export const COMBO_NAMES: ComboLevel[] = ['none', 'bronze', 'silver', 'gold', 'platinum'];
export const COMBO_LABELS: Record<ComboLevel, string> = {
  none: '',
  bronze: 'Bronze',
  silver: 'Silver',
  gold: 'Gold',
  platinum: 'Platinum',
};
export const COMBO_COLORS: Record<ComboLevel, string> = {
  none: '',
  bronze: '#d97706',
  silver: '#94a3b8',
  gold: '#fbbf24',
  platinum: '#00f0ff',
};

export function getComboLevel(combo: number): ComboLevel {
  if (combo >= 20) return 'platinum';
  if (combo >= 10) return 'gold';
  if (combo >= 5) return 'silver';
  if (combo >= 3) return 'bronze';
  return 'none';
}

export function getComboMultiplier(combo: number): number {
  const level = getComboLevel(combo);
  const idx = COMBO_NAMES.indexOf(level);
  return COMBO_MULTIPLIERS[idx];
}

export function getComboLabel(combo: number): string {
  return COMBO_LABELS[getComboLevel(combo)];
}

/* ===========================
   Learner's Den Types
   =========================== */

export type DenToolKey = 'audio' | 'mindmap' | 'presentation' | 'recall' | 'visual' | 'report';

export interface DenToolInfo {
  key: DenToolKey;
  title: string;
  description: string;
  icon: string;
  gradient: string;
}

export const DEN_TOOLS: DenToolInfo[] = [
  {
    key: 'audio',
    title: 'Audio Overview',
    description: 'Listen to your notes narrated with AI-generated commentary',
    icon: '🎧',
    gradient: 'from-purple-500/20 to-cyan-500/20',
  },
  {
    key: 'mindmap',
    title: 'Mind Map',
    description: 'Visualise connections between concepts in an interactive map',
    icon: '🧠',
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    key: 'presentation',
    title: 'Presentation',
    description: 'Review key points in a slide-based format',
    icon: '📊',
    gradient: 'from-pink-500/20 to-purple-500/20',
  },
  {
    key: 'recall',
    title: 'Recall Cards',
    description: 'Test your memory with interactive flip cards',
    icon: '🃏',
    gradient: 'from-amber-500/20 to-orange-500/20',
  },
  {
    key: 'visual',
    title: 'Visual Breakdown',
    description: 'See an infographic-style summary of your module',
    icon: '🎨',
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    key: 'report',
    title: 'Study Report',
    description: 'Generate a .docx study report with Q&A and glossary',
    icon: '📄',
    gradient: 'from-red-500/20 to-rose-500/20',
  },
];

/* ===========================
   Den Tool Content
   =========================== */

export interface AudioOverviewData {
  script: string;
  segments: { heading: string; text: string }[];
}

export interface MindMapData {
  centralTopic: string;
  branches: MindMapBranch[];
}

export interface MindMapBranch {
  label: string;
  children: string[];
}

export interface PresentationData {
  slides: SlideData[];
}

export interface SlideData {
  title: string;
  content: string;
  bulletPoints: string[];
}

export interface RecallCardsData {
  cards: RecallCardData[];
}

export interface RecallCardData {
  front: string;
  back: string;
  hint?: string;
}

export interface VisualBreakdownData {
  title: string;
  sections: VisualSection[];
}

export interface VisualSection {
  heading: string;
  icon: string;
  items: string[];
  color: string;
}

export interface StudyReportData {
  objectiveQuestions: { question: string; options: string[]; correctIndex: number }[];
  subjectiveQuestions: { question: string; sampleAnswer: string }[];
  glossary: { term: string; definition: string }[];
}

/* ===========================
   AI Provider Types
   =========================== */

export type AIProvider = 'openrouter' | 'aimlapi';

export const AI_PROVIDER_OPTIONS: { key: AIProvider; label: string }[] = [
  { key: 'openrouter', label: 'OpenRouter' },
  { key: 'aimlapi', label: 'AI/ML API' },
];

/* ===========================
   UI / App State
   =========================== */

export type TabKey = 'dashboard' | 'universe' | 'duel' | 'den';

export type ModalType = 'none' | 'apiKey' | 'notesInput';

export interface Notification {
  id: string;
  type: 'xp' | 'achievement' | 'info' | 'error';
  message: string;
  timestamp: number;
  read: boolean;
}

export interface AppState {
  hasEntered: boolean;
  apiKey: string;
  provider: AIProvider;
  apiKeyError: string | null;
  activeModuleId: string | null;
  modules: ModuleData[];
  activeTab: TabKey;
  modal: ModalType;
  isLoading: boolean;
  error: string | null;
  notifications: Notification[];
  duel: DuelState;
  activeDenTool: DenToolKey | null;
  documentImages: DocumentImage[];
}